project:
  type: website

website:
  title: "PROUD: an inclusive R community"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: meetups.qmd
        text: Meetups

format:
  html:
    theme: 
    - minty
    - style/custom.scss
    toc: true



