---
title: "Pharma R Opportunities for Under-recognised Developers (PROUD)"
description: Pharma R Opportunities for Under-recognised Developers
---

_NAME ALTERNATIVES_:  
- inclusiveR  
- spotlight/R  
- PharmaPROUD

# Who are the PROUD chairs?
Christina, Orla, Harvey. 

# What's our origin story?
TL;DR 
Rage against the patriarchy. 

In the long, long ago times of 2023 Orla and I were at a conference. As data scientist both of us decided to go to the panel on open souce. And you can imagine our astonishment when the panel came on stage and of the 11 people up there only 1 person wasn't white and only 1 person wasn't a man! 
I may never know wether it was fate or just our general aura of feminisht rage that brought us together, but we saw each other from across the room and walk towards one another and struck up a conversation. Both of us where a bit agaust about the lack of diversity on this panel. We ended up chatting for few hours about the state of open source and how concerned we were that someone wasn't trying to stop the known inequality of the open source from reaching Pharma. That's when we realised, we were probably just as qualified as anyone else to do this. So we started PROUD. 

time of change in terms of tools and tech -> people who already have the skills (exposure) progressing faster -> particular demographic overrepresented in the skills -> self-fullfilling  

only white men are driving the agenda and in a self-fullfilling... 

# What is PROUD? 
PROUD is an inclusive R community for developers who work in the pharma space. Trying to address the structural inequality that affects our community.  

# What are PROUD's objectives? 
The goals of PROUD are to provide a welcoming, equitable and supportive space for people to upskill, share knowledge and build their network. 

We are currently in a time of change in terms of tools and tech. Peple who already have these more "techy" skills will get more exposure and progress faster. Systemic inequality has made it so these skills are overrepresented in particular demographics, which is creates a self-sulling cycle. 

# How can I get involved? 

There are several ways to get involved with PROUD. We have two main tracks:

1. Build your network  
- enable conference organisers to select from a diverse pool of R developers for representations on panels, talks, etc.   
- opportunty for cross-industry collaboration with focus on inclusivity  
2. Upskilling and knowledge sharing  
- 

- slack? 
- monthly meet ups / webinars 


growing skills gap overrepresented in loud voices; 
goal is to share knowledge in an inclusive way


Overtime stats -> data scientist



